language: node_js

node_js:
  - 10
  - 8
  - 6
  - 4

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm semantic-release

branches:
  only:
    - master
