sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g semantic-release
before_script:
  - npm prune
after_success:
  - semantic-release pre && npm publish && semantic-release post
branches:
  only:
    - master
